"""Building an upstream package by running its own ./configure.

Everything up to and including coreutils had to be compiled from a source
list transcribed by hand, because no shell existed to run a configure script.
bash changes that, and from here on a package is built the way its authors
meant it to be.

Two things have to be pinned that a normal build leaves to the system.

A configure script's shebang is `#!/bin/sh`, and make runs any recipe holding
a shell metacharacter through `$(SHELL)`, which also defaults to `/bin/sh`.
Neither is sandboxed away on a normal Linux host, so both would silently pick
up the host's shell and the bootstrap would stop being a bootstrap. The driver
below invokes configure through the bash this repository built and passes that
same bash to make and to autoconf, so nothing in the build can reach /bin/sh.

Paths handed to the action are relative to the execroot, and configure runs
one directory down inside the unpacked tree. The driver turns them absolute
before descending rather than trying to count `../`s.
"""

load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("//tools/stage0:files.bzl", "tool_dir")
load("//tools/stage0:kaem.bzl", "kaem_run")

# The decompressor for each archive format, as mescc-tools-extra names them.
_DECOMPRESSORS = {
    "gz": "ungz",
    "bz2": "unbz2",
    "xz": "unxz",
}

# Which program unpacks a .gz.
#
# mescc-tools-extra's ungz is a minimal inflate built on puff, and it does not
# handle every stream a modern gzip produces -- bash 5.3's tarball makes it
# fail with "puff() failed with return code -2". Once this repository has
# built GNU gzip, that is the better answer; until then ungz is the only one
# there is, which is why gzip itself has to use it.
DECOMPRESS_SEED = "seed"
DECOMPRESS_GNU = "gnu"

_DECOMPRESSOR_KINDS = [
    DECOMPRESS_SEED,
    DECOMPRESS_GNU,
]

# Which C library's headers a package is compiled against.
#
# Everything up to now borrows mes-libc's, because it has no other. A C
# library is the exception: musl ships a complete set of its own and they have
# to be the only ones on the include path. mes-libc's would otherwise shadow
# them -- the injected -I flags come before the ones the package's own
# makefile adds -- and musl's internal headers would silently lose to
# same-named files that mean something else.
LIBC_HEADERS_MES = "mes"
LIBC_HEADERS_OWN = "own"

# The musl tinycc installs its compiler, musl's headers and musl's runtime as
# one tree, so a single directory names all three. Packages built after that
# point use this rather than the scattered mes-libc directories.
LIBC_HEADERS_TOOLCHAIN = "toolchain"

_LIBC_HEADERS = [
    LIBC_HEADERS_MES,
    LIBC_HEADERS_OWN,
    LIBC_HEADERS_TOOLCHAIN,
]

def _driver_lines(prefix, configure_flags, make_flags, build_targets, install_target, install_commands, cc_flags, exports, extra_setup, libc_headers):
    """Returns the bash driver that configures, builds and installs a package.

    Args:
        prefix: The directory the tarball unpacks into.
        configure_flags: Flags appended to ./configure.
        make_flags: Flags passed to the build and install runs of make.
        build_targets: One string of make targets per build run, so that a
            package needing staged builds can have them. Empty means a single
            run of the makefile's default target.
        install_target: The make target that installs, usually "install".
        install_commands: Shell lines that install the build products, used
            instead of running make when the install rules need tools that do
            not exist yet.
        cc_flags: Extra flags appended to the CC the package is given.
        exports: Shell assignments exported before ./configure runs.
        extra_setup: Shell lines run inside the tree before ./configure.
        libc_headers: LIBC_HEADERS_MES or LIBC_HEADERS_OWN.

    Returns:
        A list of shell lines.
    """
    lines = [
        "# Generated by configure_package. Run by the bash this repository",
        "# built, never by the host's.",
        "set -eu",
        "",
        "# Every PATH entry here is relative to the execroot, and this script",
        "# changes directory. bash remembers where it found a program and",
        "# reuses that path, so a command run before the cd would be looked",
        "# for at a stale relative path afterwards and fail with ENOENT.",
        "set +h",
        "",
        "# Every path the action supplies is relative to the execroot, and",
        "# configure runs one directory down. Absolute paths survive the cd.",
        "root=\"$PWD\"",
        "out=\"$root/$out\"",
        "",
        "# The shell for configure, for config.status and for every make",
        "# recipe that needs one. Without this all three find /bin/sh and the",
        "# host's shell enters a build that is supposed to have none.",
        "bash_path=\"$root/$(command -v bash)\"",
        "export CONFIG_SHELL=\"$bash_path\"",
        "export SHELL=\"$bash_path\"",
        "",
        "# A shell writes here-documents to a temporary file, and the action",
        "# runs with an emptied environment, so there is no TMPDIR to write",
        "# them to. autoconf builds config.status out of very large here-",
        "# documents; when they cannot be written it reports only",
        "# \"could not make ./config.status\" and stops.",
        "export TMPDIR=\"$root/tmp\"",
        "mkdir -p \"$TMPDIR\"",
        "",
        "# Make PATH absolute. The action supplies it relative to the",
        "# execroot, with a ../-prefixed copy of each entry so that a build",
        "# one directory down still resolves. That breaks down here: a",
        "# configure script descends into subdirectories to configure them,",
        "# and each depth would need a different number of ../ segments.",
        "# Anchoring every entry to the execroot makes the depth irrelevant.",
        "absolute_path=\"\"",
        "saved_ifs=\"$IFS\"",
        "IFS=:",
        "for entry in $PATH; do",
        "  while [ \"${entry#../}\" != \"$entry\" ]; do entry=\"${entry#../}\"; done",
        "  case \"$entry\" in",
        "    /*) ;;",
        "    *) entry=\"$root/$entry\" ;;",
        "  esac",
        "  absolute_path=\"$absolute_path${absolute_path:+:}$entry\"",
        "done",
        "IFS=\"$saved_ifs\"",
        "export PATH=\"$absolute_path\"",
        "",
        "# tinycc knows where its own headers live only because those paths",
        "# were baked in when it was built; they still have to be named.",
        "# tcc_include holds the compiler's own headers -- stdarg.h, stddef.h",
        "# and the rest that belong to the compiler rather than to a libc --",
        "# so it is needed whichever C library the package compiles against.",
        " ".join(
            [
                "export CC=\"tcc",
            ] + ([
                # No -I for the C library here. The compiler was built
                # knowing where musl's headers live, and finds them on its
                # system include path -- which is searched after -I, so a
                # package that ships gnulib replacements still gets its own.
                "-B $root/$toolchain/lib",
            ] if libc_headers == LIBC_HEADERS_TOOLCHAIN else [
                "-B $root/$tcc_libs",
                "-I $root/$tcc_include",
            ] + ([
                "-I $root/$mes_arch_include",
                "-I $root/$mes_include",
            ] if libc_headers == LIBC_HEADERS_MES else [])) + cc_flags,
        ) + "\"",
        "",
    ]

    for export in exports:
        lines.append("export " + export)
    if exports:
        lines.append("")

    lines += [
        "cd " + prefix,
        "",
        "# untar does not preserve the executable bit, and a configure script",
        "# needs it: it runs missing, install-sh, config.sub and the configure",
        "# scripts of subdirectories by path, not through a shell. The walk is",
        "# a shell function because findutils does not exist yet here.",
        "prepare_source_tree () {",
        "  local entry",
        "  for entry in \"$1\"/*; do",
        "    if [ -d \"$entry\" ]; then",
        "      prepare_source_tree \"$entry\"",
        "    elif [ -f \"$entry\" ]; then",
        "      case \"$entry\" in",
        "        */configure | *.sh | */missing | */install-sh | */mkinstalldirs \\",
        "        | */config.sub | */config.guess | */depcomp | */compile \\",
        "        | */move-if-change | */ylwrap | */test-driver)",
        "          chmod +x \"$entry\"",
        "          ;;",
        "      esac",
        "    fi",
        "  done",
        "}",
        "prepare_source_tree .",
        "",
        "# untar also stamps every file with the moment of extraction rather",
        "# than with what the archive recorded, so a file created immediately",
        "# afterwards can share their timestamp. autoconf's sanity check",
        "# compares its own probe against the distributed files at a",
        "# resolution of one second and stops if the probe is not strictly",
        "# newer: \"newly created file is older than distributed files\".",
        "#",
        "# Waiting for the clock to move past that second is enough. It is",
        "# done with bash's own -nt rather than with sleep or touch -t,",
        "# because both of those are broken in the mes-libc coreutils this",
        "# stage still uses -- sleep cannot read the realtime clock and",
        "# touch -t reports success without changing anything.",
        "probe=.stage0-timestamp-probe",
        ": > \"$probe\"",
        "while [ ! \"$probe\" -nt configure ]; do",
        "  : > \"$probe\"",
        "done",
        "rm -f \"$probe\"",
        "",
    ]

    if extra_setup:
        lines += extra_setup + [""]

    lines += [
        "# Configure. Naming the shell rather than running ./configure",
        "# directly does two jobs: untar does not preserve the executable bit,",
        "# and the script's own #!/bin/sh is never consulted.",
        " ".join(["\"$bash_path\"", "./configure", "--prefix=\"$out\""] + configure_flags),
        "",
        "# Build. SHELL is passed explicitly because make ignores it from the",
        "# environment by design.",
    ]

    # Each entry is one make run. Some packages have to be built in stages --
    # binutils links its libraries into the tools, and the tools do not
    # resolve unless the libraries are finished first.
    for targets in (build_targets or [""]):
        lines.append(
            " ".join(["make", "SHELL=\"$bash_path\""] + make_flags +
                     ([targets] if targets else [])),
        )
    lines.append("")

    # A package whose install rules need tools this bootstrap does not have
    # yet -- makeinfo is the usual one -- says what to copy instead.
    if install_commands:
        lines += ["# Install."] + install_commands + [""]
    else:
        lines += [
            "# Install.",
            " ".join(["make", "SHELL=\"$bash_path\"", install_target] + make_flags),
            "",
        ]
    return lines

def configure_package(
        name,
        tarball,
        prefix,
        configure_flags = [],
        make_flags = [],
        build_targets = [],
        install_target = "install",
        install_commands = [],
        cc_flags = [],
        exports = [],
        extra_setup = [],
        libc_headers = LIBC_HEADERS_MES,
        patches = [],
        patch_labels = [],
        patch_strip = 1,
        extra_tarballs = {},
        srcs = [],
        compression = "gz",
        decompressor = DECOMPRESS_SEED,
        tcc = "//tools/tcc/current:tcc",
        tcc_libs = "//tools/tcc/current:tcc_libs",
        tcc_include = "//tools/tcc/current:src_include_dir",
        tcc_src = "//tools/tcc/current:src",
        toolchain = "//tools/tcc/musl:tcc-musl",
        tools = [],
        **kwargs):
    """Builds a package by running its own ./configure, make and make install.

    Args:
        name: Target name; the output directory is what `make install` wrote.
        tarball: The source archive.
        prefix: The directory the archive unpacks into.
        configure_flags: Flags appended to ./configure.
        make_flags: Flags passed to make, for both the build and the install.
        build_targets: One string of make targets per build run, so that a
            package needing staged builds can have them. Empty means a single
            run of the makefile's default target.
        install_target: The make target that installs.
        install_commands: Shell lines that install the build products, used
            instead of running make when the install rules need tools that do
            not exist yet.
        cc_flags: Extra flags appended to the CC the package is given.
        exports: Shell assignments exported before ./configure runs.
        extra_setup: Shell lines run inside the unpacked tree before
            ./configure, for the file shuffling some packages need.
        libc_headers: LIBC_HEADERS_MES to compile against mes-libc's headers,
            or LIBC_HEADERS_OWN for a package that ships its own C library
            headers and must not see any others.
        patches: Execroot-relative paths of patch files.
        patch_labels: The same patches as labels, so they reach the action.
        patch_strip: The -p level the patches are written against.
        extra_tarballs: Further archives unpacked beside the main one, as a
            map of script-variable name to label. A package like GCC ships
            its front ends and its arbitrary-precision libraries separately.
        srcs: Additional files the build reads.
        compression: Archive compression: "gz", "bz2" or "xz".
        decompressor: DECOMPRESS_SEED for mescc-tools-extra's inflate, or
            DECOMPRESS_GNU for the gzip this repository built. The seed's
            cannot read every stream a modern gzip writes.
        tcc: The tinycc to build with.
        tcc_libs: That compiler's library directory.
        tcc_include: That compiler's own include directory.
        tcc_src: The source tree those headers belong to, staged as inputs.
        tools: Extra tool directories to put on PATH.
        **kwargs: Passed through to the underlying kaem_run.
    """
    if compression not in _DECOMPRESSORS:
        fail("unknown compression %s" % compression)
    if decompressor not in _DECOMPRESSOR_KINDS:
        fail("decompressor must be one of %s, got %s" % (_DECOMPRESSOR_KINDS, decompressor))
    if libc_headers not in _LIBC_HEADERS:
        fail("libc_headers must be one of %s, got %s" % (_LIBC_HEADERS, libc_headers))

    write_file(
        name = name + "_driver",
        out = name + "_build.sh",
        content = _driver_lines(
            prefix,
            configure_flags,
            make_flags,
            build_targets,
            install_target,
            install_commands,
            cc_flags,
            exports,
            extra_setup,
            libc_headers,
        ),
    )

    # kaem still does the unpacking and patching. It cannot cd, which is
    # exactly why the driver above exists, but it can decompress and patch
    # without any of this mattering.
    if decompressor == DECOMPRESS_GNU:
        # gzip decides the output name by dropping the suffix, which is what
        # makes this expressible in kaem: there is no redirection here, so a
        # decompressor that writes to stdout would be unusable.
        lines = [
            "# Unpack, with the gzip this repository built rather than the",
            "# seed's minimal inflate.",
            "cp ${tarball} source.tar.gz",
            "gzip -d source.tar.gz",
            "untar --file source.tar",
            "",
        ]
    else:
        lines = [
            "# Unpack.",
            "%s --file ${tarball} --output source.tar" % _DECOMPRESSORS[compression],
            "untar --file source.tar",
            "",
        ]

    # Further archives unpacked beside the main one. These always go through
    # the built gzip: a package that ships several tarballs is late enough in
    # the chain to have one.
    if extra_tarballs:
        lines.append("# Unpack the archives that travel with it.")
        for archive in sorted(extra_tarballs):
            lines += [
                "cp ${%s} %s.tar.gz" % (archive, archive),
                "gzip -d %s.tar.gz" % archive,
                "untar --file %s.tar" % archive,
            ]
        lines.append("")

    if patches:
        lines.append("# Patch, relative to the unpacked tree.")
        for patch in patches:
            lines.append("patch -d %s -Np%d -i ../%s" % (prefix, patch_strip, patch))
        lines.append("")

    lines += [
        "# Hand over to the bootstrapped shell. The driver is a generated",
        "# file under bazel-out, not a path this script could spell.",
        "mkdir -p ${out}",
        "bash ${driver}",
        "",
    ]

    write_file(
        name = name + "_script",
        out = name + ".kaem",
        content = lines,
    )

    uses_toolchain = libc_headers == LIBC_HEADERS_TOOLCHAIN

    tool_dir(
        name = name + "_tcc",
        tools = {"tcc": "//tools/tcc/musl:tcc" if uses_toolchain else tcc},
    )

    kaem_run(
        name = name,
        script = name + ".kaem",
        substitutions = dict(
            {
                "tarball": tarball,
                "driver": name + "_build.sh",
            },
            **extra_tarballs
        ),
        directory_substitutions = {"toolchain": toolchain} if uses_toolchain else {
            "tcc_libs": tcc_libs,
            "tcc_include": tcc_include,
            "mes_arch_include": "//tools/mes:arch_include_dir",
            "mes_include": "//tools/mes:header_dir",
        },
        srcs = patch_labels + [
            name + "_build.sh",
        ] + ([toolchain] if uses_toolchain else [
            tcc_src,
            "//tools/mes:arch_headers",
            "//tools/mes:header_dir",
        ]) + srcs,
        # Order matters: earlier directories win. coreutils has to come before
        # mescc-tools-extra, whose rm, cp and mkdir are single-purpose
        # stand-ins that take no options -- `rm -f` reaches the wrong one
        # otherwise and tries to delete a file called "-f".
        # A caller's extra tools come before the defaults so that a newer
        # build of something can replace the bootstrap one: sed 4.2 has to win
        # over sed 4.0.9 for any package whose configure autoconf generated.
        tools = [
            name + "_tcc",
        ] + tools + ([
            "//tools/pkg/gzip:bin",
        ] if (decompressor == DECOMPRESS_GNU or extra_tarballs) else []) + [
            "//tools/pkg/coreutils:bin",
            "//tools/pkg/bash:bin",
            "//tools/pkg/gnugrep:bin",
            "//tools/pkg/gnumake:bin",
            "//tools/pkg/gnupatch:bin",
            "//tools/pkg/gnused:bin",
            "//tools/mescc-tools-extra:bin",
        ],
        **kwargs
    )
