"""Building an upstream package by running its own ./configure.

Everything up to and including coreutils had to be compiled from a source
list transcribed by hand, because no shell existed to run a configure script.
bash changes that, and from here on a package is built the way its authors
meant it to be.

Two things have to be pinned that a normal build leaves to the system.

A configure script's shebang is `#!/bin/sh`, and make runs any recipe holding
a shell metacharacter through `$(SHELL)`, which also defaults to `/bin/sh`.
Neither is sandboxed away on a normal Linux host, so both would silently pick
up the host's shell and the bootstrap would stop being a bootstrap. The driver
below invokes configure through the bash this repository built and passes that
same bash to make and to autoconf, so nothing in the build can reach /bin/sh.

Paths handed to the action are relative to the execroot, and configure runs
one directory down inside the unpacked tree. The driver turns them absolute
before descending rather than trying to count `../`s.
"""

load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("//tools/stage0:files.bzl", "tool_dir")
load("//tools/stage0:kaem.bzl", "kaem_run")

# The decompressor for each archive format, as mescc-tools-extra names them.
_DECOMPRESSORS = {
    "gz": "ungz",
    "bz2": "unbz2",
    "xz": "unxz",
}

# Which C library's headers a package is compiled against.
#
# Everything up to now borrows mes-libc's, because it has no other. A C
# library is the exception: musl ships a complete set of its own and they have
# to be the only ones on the include path. mes-libc's would otherwise shadow
# them -- the injected -I flags come before the ones the package's own
# makefile adds -- and musl's internal headers would silently lose to
# same-named files that mean something else.
LIBC_HEADERS_MES = "mes"
LIBC_HEADERS_OWN = "own"

# The musl tinycc installs its compiler, musl's headers and musl's runtime as
# one tree, so a single directory names all three. Packages built after that
# point use this rather than the scattered mes-libc directories.
LIBC_HEADERS_TOOLCHAIN = "toolchain"

_LIBC_HEADERS = [
    LIBC_HEADERS_MES,
    LIBC_HEADERS_OWN,
    LIBC_HEADERS_TOOLCHAIN,
]

def _driver_lines(prefix, configure_flags, make_flags, build_targets, install_target, install_commands, cc_flags, exports, extra_setup, libc_headers):
    """Returns the bash driver that configures, builds and installs a package.

    Args:
        prefix: The directory the tarball unpacks into.
        configure_flags: Flags appended to ./configure.
        make_flags: Flags passed to the build and install runs of make.
        build_targets: Targets for the build run of make; empty means the
            makefile's default.
        install_target: The make target that installs, usually "install".
        install_commands: Shell lines that install the build products, used
            instead of running make when the install rules need tools that do
            not exist yet.
        cc_flags: Extra flags appended to the CC the package is given.
        exports: Shell assignments exported before ./configure runs.
        extra_setup: Shell lines run inside the tree before ./configure.
        libc_headers: LIBC_HEADERS_MES or LIBC_HEADERS_OWN.

    Returns:
        A list of shell lines.
    """
    lines = [
        "# Generated by configure_package. Run by the bash this repository",
        "# built, never by the host's.",
        "set -eu",
        "",
        "# Every path the action supplies is relative to the execroot, and",
        "# configure runs one directory down. Absolute paths survive the cd.",
        "root=\"$PWD\"",
        "out=\"$root/$out\"",
        "",
        "# The shell for configure, for config.status and for every make",
        "# recipe that needs one. Without this all three find /bin/sh and the",
        "# host's shell enters a build that is supposed to have none.",
        "bash_path=\"$root/$(command -v bash)\"",
        "export CONFIG_SHELL=\"$bash_path\"",
        "export SHELL=\"$bash_path\"",
        "",
        "# tinycc knows where its own headers live only because those paths",
        "# were baked in when it was built; they still have to be named.",
        "# tcc_include holds the compiler's own headers -- stdarg.h, stddef.h",
        "# and the rest that belong to the compiler rather than to a libc --",
        "# so it is needed whichever C library the package compiles against.",
        " ".join(
            [
                "export CC=\"tcc",
            ] + ([
                "-B $root/$toolchain/lib",
                "-I $root/$toolchain/include",
            ] if libc_headers == LIBC_HEADERS_TOOLCHAIN else [
                "-B $root/$tcc_libs",
                "-I $root/$tcc_include",
            ] + ([
                "-I $root/$mes_arch_include",
                "-I $root/$mes_include",
            ] if libc_headers == LIBC_HEADERS_MES else [])) + cc_flags,
        ) + "\"",
        "",
    ]

    for export in exports:
        lines.append("export " + export)
    if exports:
        lines.append("")

    lines += [
        "cd " + prefix,
        "",
        "# untar does not preserve the executable bit, and a configure script",
        "# runs its helpers -- missing, install-sh, config.sub, and the",
        "# configure scripts of subdirectories -- by path rather than through",
        "# a shell. Anything meant to be run has to get that bit back.",
        "#",
        "# The walk is a shell function because findutils does not exist yet",
        "# at this point in the bootstrap.",
        "restore_executable_bits () {",
        "  local entry",
        "  for entry in \"$1\"/*; do",
        "    if [ -d \"$entry\" ]; then",
        "      restore_executable_bits \"$entry\"",
        "    elif [ -f \"$entry\" ]; then",
        "      case \"$entry\" in",
        "        */configure | *.sh | */missing | */install-sh | */mkinstalldirs \\",
        "        | */config.sub | */config.guess | */depcomp | */compile \\",
        "        | */move-if-change | */ylwrap | */test-driver)",
        "          chmod +x \"$entry\"",
        "          ;;",
        "      esac",
        "    fi",
        "  done",
        "}",
        "restore_executable_bits .",
        "",
    ]

    if extra_setup:
        lines += extra_setup + [""]

    lines += [
        "# Configure. Naming the shell rather than running ./configure",
        "# directly does two jobs: untar does not preserve the executable bit,",
        "# and the script's own #!/bin/sh is never consulted.",
        " ".join(["\"$bash_path\"", "./configure", "--prefix=\"$out\""] + configure_flags),
        "",
        "# Build. SHELL is passed explicitly because make ignores it from the",
        "# environment by design.",
        " ".join(["make", "SHELL=\"$bash_path\""] + make_flags + build_targets),
        "",
    ]

    # A package whose install rules need tools this bootstrap does not have
    # yet -- makeinfo is the usual one -- says what to copy instead.
    if install_commands:
        lines += ["# Install."] + install_commands + [""]
    else:
        lines += [
            "# Install.",
            " ".join(["make", "SHELL=\"$bash_path\"", install_target] + make_flags),
            "",
        ]
    return lines

def configure_package(
        name,
        tarball,
        prefix,
        configure_flags = [],
        make_flags = [],
        build_targets = [],
        install_target = "install",
        install_commands = [],
        cc_flags = [],
        exports = [],
        extra_setup = [],
        libc_headers = LIBC_HEADERS_MES,
        patches = [],
        patch_labels = [],
        patch_strip = 1,
        srcs = [],
        compression = "gz",
        tcc = "//tools/tcc/current:tcc",
        tcc_libs = "//tools/tcc/current:tcc_libs",
        tcc_include = "//tools/tcc/current:src_include_dir",
        tcc_src = "//tools/tcc/current:src",
        toolchain = "//tools/tcc/musl:tcc-musl",
        tools = [],
        **kwargs):
    """Builds a package by running its own ./configure, make and make install.

    Args:
        name: Target name; the output directory is what `make install` wrote.
        tarball: The source archive.
        prefix: The directory the archive unpacks into.
        configure_flags: Flags appended to ./configure.
        make_flags: Flags passed to make, for both the build and the install.
        build_targets: Targets for the build run of make; empty means the
            makefile's default target.
        install_target: The make target that installs.
        install_commands: Shell lines that install the build products, used
            instead of running make when the install rules need tools that do
            not exist yet.
        cc_flags: Extra flags appended to the CC the package is given.
        exports: Shell assignments exported before ./configure runs.
        extra_setup: Shell lines run inside the unpacked tree before
            ./configure, for the file shuffling some packages need.
        libc_headers: LIBC_HEADERS_MES to compile against mes-libc's headers,
            or LIBC_HEADERS_OWN for a package that ships its own C library
            headers and must not see any others.
        patches: Execroot-relative paths of patch files.
        patch_labels: The same patches as labels, so they reach the action.
        patch_strip: The -p level the patches are written against.
        srcs: Additional files the build reads.
        compression: Archive compression: "gz", "bz2" or "xz".
        tcc: The tinycc to build with.
        tcc_libs: That compiler's library directory.
        tcc_include: That compiler's own include directory.
        tcc_src: The source tree those headers belong to, staged as inputs.
        tools: Extra tool directories to put on PATH.
        **kwargs: Passed through to the underlying kaem_run.
    """
    if compression not in _DECOMPRESSORS:
        fail("unknown compression %s" % compression)
    if libc_headers not in _LIBC_HEADERS:
        fail("libc_headers must be one of %s, got %s" % (_LIBC_HEADERS, libc_headers))

    write_file(
        name = name + "_driver",
        out = name + "_build.sh",
        content = _driver_lines(
            prefix,
            configure_flags,
            make_flags,
            build_targets,
            install_target,
            install_commands,
            cc_flags,
            exports,
            extra_setup,
            libc_headers,
        ),
    )

    # kaem still does the unpacking and patching. It cannot cd, which is
    # exactly why the driver above exists, but it can decompress and patch
    # without any of this mattering.
    lines = [
        "# Unpack.",
        "%s --file ${tarball} --output source.tar" % _DECOMPRESSORS[compression],
        "untar --file source.tar",
        "",
    ]

    if patches:
        lines.append("# Patch, relative to the unpacked tree.")
        for patch in patches:
            lines.append("patch -d %s -Np%d -i ../%s" % (prefix, patch_strip, patch))
        lines.append("")

    lines += [
        "# Hand over to the bootstrapped shell. The driver is a generated",
        "# file under bazel-out, not a path this script could spell.",
        "mkdir -p ${out}",
        "bash ${driver}",
        "",
    ]

    write_file(
        name = name + "_script",
        out = name + ".kaem",
        content = lines,
    )

    uses_toolchain = libc_headers == LIBC_HEADERS_TOOLCHAIN

    tool_dir(
        name = name + "_tcc",
        tools = {"tcc": "//tools/tcc/musl:tcc" if uses_toolchain else tcc},
    )

    kaem_run(
        name = name,
        script = name + ".kaem",
        substitutions = {
            "tarball": tarball,
            "driver": name + "_build.sh",
        },
        directory_substitutions = {"toolchain": toolchain} if uses_toolchain else {
            "tcc_libs": tcc_libs,
            "tcc_include": tcc_include,
            "mes_arch_include": "//tools/mes:arch_include_dir",
            "mes_include": "//tools/mes:header_dir",
        },
        srcs = patch_labels + [
            name + "_build.sh",
        ] + ([toolchain] if uses_toolchain else [
            tcc_src,
            "//tools/mes:arch_headers",
            "//tools/mes:header_dir",
        ]) + srcs,
        # Order matters: earlier directories win. coreutils has to come before
        # mescc-tools-extra, whose rm, cp and mkdir are single-purpose
        # stand-ins that take no options -- `rm -f` reaches the wrong one
        # otherwise and tries to delete a file called "-f".
        tools = [
            name + "_tcc",
            "//tools/pkg/coreutils:bin",
            "//tools/pkg/bash:bin",
            "//tools/pkg/gnugrep:bin",
            "//tools/pkg/gnumake:bin",
            "//tools/pkg/gnupatch:bin",
            "//tools/pkg/gnused:bin",
            "//tools/mescc-tools-extra:bin",
        ] + tools,
        **kwargs
    )
